### ISSUE TITLE
 cannot find the file

### ISSUE THREAD

**Issue by YJY-0718** [gustavocidornelas/fused-multimodal-emotion#11]
I cannot find the file' FC_ordered_ids.txt' while running the code 'prepare_raw_audio',I want to know if there is some other code to run this' FC_ordered_ids.txt'?

**Comment by gustavocidornelas** [comment]
Hi! The file 'FC_ordered_ids.txt' is part of the preprocessed data that you need to train the model. The code to generate these preprocessed files from the raw IEMOCAP dataset is not included in this repository, as I did not preprocess them myself.

If you want, I can send you all the preprocessed files and you can just place them inside the correct directory (see the readme in /data). The IEMOCAP dataset is protected by a license, so make sure that you already have access to it. You can email me at cgustavo@student.ethz.ch showing that you already have access to the IEMOCAP dataset (it can be a screenshot, just to make sure that you have the license) and I'll be happy to share the preprocessed files with you.
